# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_power:
#   ignored: false
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_energy:
#   ignored: false
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_temperature:
#   ignored: false
#   polling_intensity: 0
# climate.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_mode:
#   ignored: false
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_exporting:
#   ignored: true
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_exhaust_temperature:
#   ignored: true
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_luminance:
#   ignored: true
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_relative_humidity:
#   ignored: true
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_interval:
#   ignored: true
#   polling_intensity: 0
# sensor.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_previous_reading:
#   ignored: true
#   polling_intensity: 0
